global:
  scrape_interval: 15s

scrape_configs:


  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - '192.168.171.144:8086'
  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.171.144:8080']
  
  - job_name: 'spring_actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.171.144:8082']
